/*
 * generated by Xtext 2.13.0
 */
package ma.kvmod.pidm.lang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PidmLangRuntimeModule extends AbstractPidmLangRuntimeModule {
}
