/*
 * generated by Xtext 2.13.0
 */
package ma.kvmod.pidm.lang.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(PidmLangInjectorProvider)
class PidmLangParsingTest {
//	@Inject
//	ParseHelper<Model> parseHelper
	
	@Test
	def void loadModel() {
	}
}
