/*
 * generated by Xtext 2.13.0
 */
package ma.kvmod.pidm.lang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class PidmLangUiModule extends AbstractPidmLangUiModule {
}
