/*
 * generated by Xtext 2.13.0
 */
package ma.kvmod.pidm.lang.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class PidmLangWebModule extends AbstractPidmLangWebModule {
}
